### PR TITLE
New Python module

### PR DESCRIPTION
**Pull request by samalba**
Here is my new module

### CODE REVIEW

**Comment by vbehar** [comment]
where's your README? ;-)

**Comment by shykes** [comment]
LGTM

**Comment by shykes** [comment]
https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExbDlmeWlleXl3amttNTN6bWZrZDA3OTdjaTRtNXEyamM2c2x3N2czdiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/143vPc6b08locw/giphy.gif

**Comment by samalba** [comment]
!dagger -m github.com/kpenfound/dagger-modules/ruff@4c9d04b461f9e0fce3ff40399570f635f586d972 call check --directory ./my-new-python-mod

Hey, Sam did not build any test, trying with Ruff



---

`$ dagger -m github.com/kpenfound/dagger-modules/ruff@4c9d04b461f9e0fce3ff40399570f635f586d972 call check --directory ./my-new-python-mod`

```
Error: response from query: input: ruff.check call function "check": process "/runtime" did not complete successfully: exit code: 1

Stderr:
╭─ Error ──────────────────────────────────────────────────────────────────────╮
│ Function execution error: process "ruff check ." did not complete            │
│ successfully: exit code: 1                                                   │
│ Stdout:                                                                      │
│ src/main.py:30:7: E999 SyntaxError: unindent does not match any outer        │
│ indentation level                                                            │
│ Found 1 error.                                                               │
│ Stderr:                                                                      │
│ error: Failed to parse src/main.py:30:7: unindent does not match any outer   │
│ indentation level                                                            │
╰──────────────────────────────────────────────────────────────────────────────╯

```

**Comment by vbehar** [comment]
!sh cat /etc/passwd

**Comment by sagikazarmark** [comment]
!sh echo $GITHUB_TOKEN

**Comment by samalba** [comment]
Thanks @shykes @sagikazarmark @vbehar for making this demo better 😃

**Pull request closed without merging**
